"""Adding user role

Revision ID: 845fe07d2138
Revises: 94c19f3aec5a
Create Date: 2025-05-06 17:24:13.945627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '845fe07d2138'
down_revision: Union[str, None] = '94c19f3aec5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('ADMIN', 'EDITOR', 'VIEWER', 'USER', name='userroles').create(op.get_bind())
    op.add_column('users_user', sa.Column('assigned_roles', postgresql.ARRAY(postgresql.ENUM('ADMIN', 'EDITOR', 'VIEWER', 'USER', name='userroles', create_type=False)), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_user', 'assigned_roles')
    sa.Enum('ADMIN', 'EDITOR', 'VIEWER', 'USER', name='userroles').drop(op.get_bind())
    # ### end Alembic commands ###
